name: "Unit Testing and Code Coverage"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: "3.10"

      - name: install dependencies
        run: python -m pip install -r requirements.txt

      - name: run unit tests
        run: pytest ./parameterized/tests/

      - name: generate coverage report
        run: |
          coverage run -m pytest ./parameterized/tests/
          coverage xml

      - name: generate coverage badge
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          move_coverage_to_trash: true
